[package]
name = "breakout"
version = "0.1.0"
authors = ["Simon Voordouw <simonvoordouw@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version="0.9", features=["wayland"] }
bevy-inspector-egui = "0.17.0"
iyes_loopless = { version = "0.9.1", features = ["bevy-inspector-egui"] }
